@startuml

actor Controller

Controller -> moveCabinCommand: execute(HashMap<String, String>)
activate moveCabinCommand
moveCabinCommand -> Engine: change engineState to GOING_DOWN
deactivate moveCabinCommand

@enduml
