@startuml

actor Controller

Controller -> openDoorCommand: execute(HashMap<String, String>)
activate openDoorCommand
openDoorCommand -> Controller: doorOpeningRestriction()
Controller --> openDoorCommand: successful
openDoorCommand -> Cabin: change doorState to OPENED
deactivate openDoorCommand

@enduml
