@startuml

actor PressFloorButton

PressFloorButton -> Controller: findNearestCabin((floor: int)
activate Controller
Controller -> Shaft: addSequence()
Shaft --> Controller: successful
deactivate Controller
@enduml
