@startuml

actor Invoker

Invoker -> checkCabinDirectionCommand: execute
activate checkCabinDirectionCommand
checkCabinDirectionCommand -> Controller: checkCabinDirectionCommand(Direction: direction)
Controller -> Controller: checkCabinDirection()
Controller -> Shaft:
deactivate checkCabinDirectionCommand

@enduml
